export const SHOP_CONFIG = {
  shopDomain: 'sketch-us.myshopify.com',
  variantId: '58043598831880',
  price: '€9,99',
  vercelUrl: 'https://sketchus-portrait-generator.vercel.app',
  originalPortraitUrl: 'https://sketchus.de/products/portrait-zeichnen-lassen',
  maxPreviewsPerDay: 10,
  imageAspectRatio: 297 / 210,
  estimatedLoadingMs: 55000,
};

export const DESIGN = {
  colors: {
    pageBg: '#636363',
    cardBg: '#636363',
    accent: '#ffffff',
    accentText: '#1a1a1a',
    buyBtn: '#ffffff',
    buyBtnText: '#1a1a1a',
    text: '#ffffff',
    textMuted: '#eeeeee',
    textDim: '#cccccc',
    border: 'rgba(255,255,255,0.35)',
    linkColor: '#ffffff',
    error: '#ff6b6b',
    overlayBg: 'rgba(99,99,99,0.97)',
  },
  font: '"Helvetica Neue", Arial, sans-serif',
  borderRadius: { card: 0, btn: 4, upload: 4, modal: 8 },
};

export const TRANSLATIONS = {
  de: {
    title: 'Bleistift-Portrait Vorschau',
    subtitle: 'Lade dein Foto hoch und erhalte eine automatische Vorschau deines Portraits',
    counter: (count, max) => `${count} von ${max} kostenlosen Vorschauen`,
    upload: 'Foto hochladen',
    uploadHint: 'JPG, PNG oder WEBP · Klicken oder hierher ziehen',
    changePhoto: 'Anderes Foto wählen',
    generate: 'Vorschau erstellen',
    generating: 'Vorschau wird erstellt…',
    cropTitle: 'Bildausschnitt wählen',
    cropSave: 'Übernehmen',
    cropCancel: 'Abbrechen',
    zoom: 'Zoom',
    resultLabel: 'Automatische Vorschau (mit Wasserzeichen):',
    sizeNote: 'Format: A4 Querformat · Diese Vorschau wird automatisch erstellt',
    buyBtn: (price) => `Jetzt bestellen — ${price}`,
    upsellText: 'Möchtest du ein echtes handgezeichnetes Portrait von einem echten Künstler?',
    upsellLink: '→ Hier klicken für ein Original von Hand gezeichnet',
    loadingHeadline: 'DEINE VORSCHAU WIRD ERSTELLT',
    loadingSteps: [
      'Foto wird vorbereitet',
      'Vorschau wird generiert',
      'Details werden verfeinert',
      'Fast fertig',
    ],
    loadingUpsell: () => 'Diese Vorschau wird automatisch erstellt. Für ein echtes handgezeichnetes Original — von echten Künstlern für dich persönlich gezeichnet.',
    limitReached: (max) => `Du hast ${max} kostenlose Vorschauen verwendet.`,
    errorGeneric: 'Fehler beim Erstellen. Bitte erneut versuchen.',
    historyTitle: 'Zuletzt erstellte Portraits',
historyBtn: 'Frühere Vorschauen',
historySelect: 'Diese auswählen',
  },
  en: {
    title: 'Pencil Portrait Preview',
    subtitle: 'Upload your photo and get an automatic preview of your portrait',
    counter: (count, max) => `${count} of ${max} free previews used`,
    upload: 'Upload photo',
    uploadHint: 'JPG, PNG or WEBP · Click or drag here',
    changePhoto: 'Choose different photo',
    generate: 'Create preview',
    generating: 'Creating preview…',
    cropTitle: 'Choose crop',
    cropSave: 'Apply',
    cropCancel: 'Cancel',
    zoom: 'Zoom',
    resultLabel: 'Automatic preview (with watermark):',
    sizeNote: 'Format: A4 landscape · This preview is generated automatically',
    buyBtn: (price) => `Order now — ${price}`,
    upsellText: 'Want a real hand-drawn portrait by a real artist?',
    upsellLink: '→ Click here for an original hand-drawn portrait',
    loadingHeadline: 'YOUR PREVIEW IS BEING CREATED',
    loadingSteps: [
      'Preparing photo',
      'Generating preview',
      'Refining details',
      'Almost done',
    ],
    loadingUpsell: () => 'This preview is generated automatically. For a real hand-drawn original — drawn personally for you by real artists.',
    limitReached: (max) => `You have used ${max} free previews.`,
    errorGeneric: 'Error creating preview. Please try again.',
historyTitle: 'Recently created portraits',
historyBtn: 'Previous previews',
historySelect: 'Select this one',
  },
};

export const AI_PROMPT = `Convert this photo into a highly detailed pencil sketch portrait. 
Black and white, hand-drawn pencil drawing style, fine pencil strokes, 
hatching and cross-hatching shading, realistic facial features, 
pure pencil on white paper. No color.`;
