export const SHOP_CONFIG = {
  shopDomain: 'sketch-us.myshopify.com',
  variantId: '58043598831880',
  price: '€9,99',
  originalPortraitUrl: 'https://sketchus.de/products/portrait-zeichnen-lassen',
  maxPreviews: 10,
  estimatedMs: 55000,
};

export const DESIGN = {
  bg: '#636363',
  font: '"Helvetica Neue", Arial, sans-serif',
  text: '#ffffff',
  textMuted: '#eeeeee',
  textDim: '#cccccc',
  border: 'rgba(255,255,255,0.3)',
  error: '#ff6b6b',
  btn: 4,
};

export const AI_PROMPT = `Convert this photo into a highly detailed pencil sketch portrait. Black and white, hand-drawn pencil drawing style, fine pencil strokes, hatching and cross-hatching shading, realistic facial features, pure pencil on white paper. No color.`;

export const LANG = {
  de: {
    title: 'Bleistift-Portrait Vorschau',
    sub: 'Lade dein Foto hoch — erhalte eine automatische Vorschau',
    counter: (n, m) => `${n} von ${m} kostenlosen Vorschauen`,
    upload: 'Foto hochladen',
    uploadHint: 'JPG, PNG oder WEBP',
    change: 'Anderes Foto',
    cropTitle: 'Ausschnitt wählen',
    cropSave: 'Übernehmen',
    cropCancel: 'Abbrechen',
    zoom: 'Zoom',
    toPortrait: '↕ Hochformat',
    toLandscape: '↔ Querformat',
    generate: 'Vorschau erstellen',
    resultLabel: 'Deine Vorschau:',
    download: '⬇ Herunterladen',
    addToCart: `In den Warenkorb — €9,99`,
    addingToCart: 'Wird hinzugefügt…',
    cartSuccess: '✓ Im Warenkorb! Scrolle nach oben zum Checkout.',
    regenerate: 'Neue Vorschau erstellen',
    history: (n) => `🕐 Frühere Vorschauen (${n})`,
    historyTitle: 'Deine Vorschauen',
    historySelect: 'Auswählen',
    upsell: 'Lieber ein echtes handgezeichnetes Original?',
    upsellLink: '→ Hier klicken',
    loadingSteps: ['Foto wird vorbereitet', 'Skizze wird generiert', 'Details werden verfeinert', 'Fast fertig'],
    loadingNote: 'Diese Vorschau wird automatisch erstellt. Für ein echtes Original — von echten Künstlern.',
    limitMsg: (m) => `Limit von ${m} Vorschauen erreicht.`,
    errGeneric: 'Fehler. Bitte erneut versuchen.',
    cartErr: 'Fehler beim Hinzufügen. Bitte erneut versuchen.',
  },
  en: {
    title: 'Pencil Portrait Preview',
    sub: 'Upload your photo — get an automatic preview',
    counter: (n, m) => `${n} of ${m} free previews`,
    upload: 'Upload photo',
    uploadHint: 'JPG, PNG or WEBP',
    change: 'Change photo',
    cropTitle: 'Choose crop',
    cropSave: 'Apply',
    cropCancel: 'Cancel',
    zoom: 'Zoom',
    toPortrait: '↕ Portrait',
    toLandscape: '↔ Landscape',
    generate: 'Create preview',
    resultLabel: 'Your preview:',
    download: '⬇ Download',
    addToCart: `Add to Cart — €9,99`,
    addingToCart: 'Adding…',
    cartSuccess: '✓ Added! Scroll up to checkout.',
    regenerate: 'Create new preview',
    history: (n) => `🕐 Previous previews (${n})`,
    historyTitle: 'Your previews',
    historySelect: 'Select',
    upsell: 'Want a real hand-drawn original?',
    upsellLink: '→ Click here',
    loadingSteps: ['Preparing photo', 'Generating sketch', 'Refining details', 'Almost done'],
    loadingNote: 'This preview is generated automatically. For a real hand-drawn original — by real artists.',
    limitMsg: (m) => `Limit of ${m} previews reached.`,
    errGeneric: 'Error. Please try again.',
    cartErr: 'Error adding to cart. Please try again.',
  },
};
