export const SHOP_CONFIG = {
  shopDomain: 'sketch-us.myshopify.com',
  variantId: '58043598831880',
  price: '€9,99',
  originalPortraitUrl: 'https://sketchus.de/products/portrait-zeichnen-lassen',
  maxPreviewsPerDay: 10,
  estimatedLoadingMs: 55000,
};

export const DESIGN = {
  colors: {
    pageBg: '#636363',
    accent: '#ffffff',
    accentText: '#1a1a1a',
    buyBtn: '#ffffff',
    buyBtnText: '#1a1a1a',
    text: '#ffffff',
    textMuted: '#eeeeee',
    textDim: '#cccccc',
    border: 'rgba(255,255,255,0.35)',
    error: '#ff6b6b',
  },
  font: '"Helvetica Neue", Arial, sans-serif',
  btn: 4,
};

export const T = {
  de: {
    title: 'Bleistift-Portrait Vorschau',
    subtitle: 'Lade dein Foto hoch und erhalte eine automatische Vorschau',
    counter: (n, max) => `${n} von ${max} kostenlosen Vorschauen verwendet`,
    upload: 'Foto hochladen',
    uploadHint: 'JPG, PNG oder WEBP · Tippen oder hierher ziehen',
    changePhoto: 'Anderes Foto wählen',
    generate: 'Vorschau erstellen',
    generating: 'Wird erstellt…',
    cropTitle: 'Bildausschnitt wählen',
    cropSave: 'Übernehmen',
    cropCancel: 'Abbrechen',
    zoom: 'Zoom',
    toPortrait: '↕ Hochformat',
    toLandscape: '↔ Querformat',
    resultLabel: 'Deine automatische Vorschau:',
    buyBtn: (price) => `Jetzt bestellen — ${price}`,
    buyLoading: 'Wird hinzugefügt…',
    regenerate: 'Neue Vorschau erstellen',
    historyBtn: (n) => `🕐 Frühere Vorschauen (${n})`,
    historyTitle: 'Deine Vorschauen',
    historySelect: 'Auswählen',
    historyOrder: (price) => `Bestellen — ${price}`,
    upsellText: 'Möchtest du ein echtes handgezeichnetes Original?',
    upsellLink: '→ Hier klicken — von echten Künstlern gezeichnet',
    loadingHeadline: 'DEINE VORSCHAU WIRD ERSTELLT',
    loadingSteps: ['Foto wird vorbereitet', 'Skizze wird generiert', 'Details werden verfeinert', 'Fast fertig'],
    loadingNote: 'Diese Vorschau wird automatisch erstellt. Für ein echtes handgezeichnetes Original — von echten Künstlern.',
    limitReached: (max) => `Du hast ${max} kostenlose Vorschauen verwendet.`,
    error: 'Fehler beim Erstellen. Bitte erneut versuchen.',
    cartError: 'Fehler beim Hinzufügen. Bitte erneut versuchen.',
  },
  en: {
    title: 'Pencil Portrait Preview',
    subtitle: 'Upload your photo and get an automatic preview',
    counter: (n, max) => `${n} of ${max} free previews used`,
    upload: 'Upload photo',
    uploadHint: 'JPG, PNG or WEBP · Tap or drag here',
    changePhoto: 'Choose different photo',
    generate: 'Create preview',
    generating: 'Creating…',
    cropTitle: 'Choose crop',
    cropSave: 'Apply',
    cropCancel: 'Cancel',
    zoom: 'Zoom',
    toPortrait: '↕ Portrait',
    toLandscape: '↔ Landscape',
    resultLabel: 'Your automatic preview:',
    buyBtn: (price) => `Order now — ${price}`,
    buyLoading: 'Adding…',
    regenerate: 'Create new preview',
    historyBtn: (n) => `🕐 Previous previews (${n})`,
    historyTitle: 'Your previews',
    historySelect: 'Select',
    historyOrder: (price) => `Order — ${price}`,
    upsellText: 'Want a real hand-drawn original?',
    upsellLink: '→ Click here — drawn by real artists',
    loadingHeadline: 'CREATING YOUR PREVIEW',
    loadingSteps: ['Preparing photo', 'Generating sketch', 'Refining details', 'Almost done'],
    loadingNote: 'This preview is generated automatically. For a real hand-drawn original — by real artists.',
    limitReached: (max) => `You have used ${max} free previews.`,
    error: 'Error creating preview. Please try again.',
    cartError: 'Error adding to cart. Please try again.',
  },
};

export const AI_PROMPT = `Convert this photo into a highly detailed pencil sketch portrait. Black and white, hand-drawn pencil drawing style, fine pencil strokes, hatching and cross-hatching shading, realistic facial features, pure pencil on white paper. No color.`;
